name: Docs

on:
  pull_request:

jobs:
  publish-docs:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uvx mkdocs gh-deploy --force
